### ISSUE TITLE
LUFA Problem

### ISSUE THREAD

**Issue by LAZE123456789** [DavidPagels/n64-arduino-switch#2]
I am trying to compile your project as discribed by you, but i get following error.
exit status 1
LUFA/Drivers/USB/USB.h: No such file or directory
how did you add LUFA to your project ?

**Comment by dferramosi** [comment]
how did this get resolved?

**Comment by LAZE123456789** [comment]
I opened the Project the wrong way. The N64Simplified.ino should be in its own subfolder like \n64-arduino-switch-master\N64Simplified . I hope this was the fix. I am not sure anymore

**Comment by dferramosi** [comment]
That did it! Thanks!
